import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavWrapper from "@/components/NavBar/NavWrapper";
import ReduxProvider from "@/provider/reduxProvider";
import AutoLogin from "@/components/Auth/AutoLogin";
import QueryProvider from "@/provider/queryProvider";
import LoadingWrapper from "@/components/Spinner/LoadingWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shopee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <QueryProvider>
            <LoadingWrapper />
            <AutoLogin />
            <NavWrapper />

            {children}
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
